/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package FormInternos;

import accesodatos.IngresosADN;
import entidades.Formatos;
import entidades.Ingresos;
import java.sql.Date;
import java.text.ParseException;
import javax.swing.JOptionPane;
import org.validacion.Controles.DateTimeDS;

/**
 *
 * @author Crixuz
 */
public class JIIngresos extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIIngresos
     */
    public JIIngresos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtnRegistrar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtfdMotivo = new org.swing.componet.JTextBoxHintDS();
        jdprFecha = new com.michaelbaranov.microba.calendar.DatePicker();
        jtfdnro = new org.swing.componet.JTextBoxHintDS();

        setClosable(true);
        setTitle(">>:: Ingreso de Dinero ::<<");

        jbtnRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/register.png"))); // NOI18N
        jbtnRegistrar.setText("Registrar");
        jbtnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRegistrarActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Ingresar Datos"));

        jLabel1.setText("Motivo:");

        jLabel2.setText("Monto:");

        jLabel7.setText("Fecha:");

        jtfdMotivo.setHint("Ingrese su Motivo");
        jtfdMotivo.setTipoTextBox(null);
        jtfdMotivo.setTiponumero(null);

        jtfdnro.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtfdnro.setLength(11);
        jtfdnro.setTiponumero(org.Interfaces.Enum.TiposNumeros.Decimal);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jtfdMotivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jtfdnro, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(83, 83, 83))
                                    .addComponent(jdprFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addContainerGap(24, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfdMotivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfdnro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jdprFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(jbtnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnRegistrar)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRegistrarActionPerformed
       try {
            String motivo = jtfdMotivo.getText().trim().toUpperCase();
            if (IngresosADN.EvaluarApertura(Hoy()) && motivo.equals("APERTURA")) {
                JOptionPane.showMessageDialog(rootPane, "No puede aperturar caja dos veces en el mismo dia");
            } else {
                if (motivo.length() == 0) {
                    JOptionPane.showMessageDialog(rootPane, "Asegures de ingresar el motivo correctamente");
                } else {
                    if (Float.parseFloat(Formatos.df.format(Float.parseFloat(jtfdnro.getText().toString()))) <= 0.0f) {
                        JOptionPane.showMessageDialog(rootPane, "Debe ingresar un valor positivo");
                    } else {
                        String fec = Formatos.sdfFecha.format(jdprFecha.getDate());
                        Date fechasql = Formatos.FechaSQL(fec);
                        float monto = Float.parseFloat(Formatos.df.format(Float.parseFloat(jtfdnro.getText().toString())));
                        boolean gua = IngresosADN.Guardar(new Ingresos(0, fechasql, monto, motivo,null,"",""));
                        if (gua) {
                            JOptionPane.showMessageDialog(rootPane, "Ingreso a caja registrado correctamente");
                            JIVentas.apertura = true;
                            dispose();
                        }
                    }

                }

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.toString());
        }
    }//GEN-LAST:event_jbtnRegistrarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtnRegistrar;
    private com.michaelbaranov.microba.calendar.DatePicker jdprFecha;
    private org.swing.componet.JTextBoxHintDS jtfdMotivo;
    private org.swing.componet.JTextBoxHintDS jtfdnro;
    // End of variables declaration//GEN-END:variables

        static Date Hoy() throws ParseException {
        String fecha1 = Formatos.sdfFecha.format(new java.util.Date());
        Date fechasql = Formatos.FechaSQL(fecha1);
        return fechasql;
    }
}
