package FormInternos;

import accesodatos.*;
import entidades.*;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileFilter;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.sql.SQLException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import org.validacion.Controles.PanelDS;
import org.validacion.Controles.TextFieldDS;

/**
 *
 * @author Crixuz
 */
public class JIRestauraBackup extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIClientes
     */
    public JIRestauraBackup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jtfdMarcaB = new org.swing.componet.JTextBoxHintDS();
        jLabel2 = new javax.swing.JLabel();
        jbtnActivar = new javax.swing.JButton();
        jbtnGuardar = new javax.swing.JButton();

        setClosable(true);
        setResizable(true);
        setTitle(">>>>:::::: Restauración de BK ::::::<<<<");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Buscar Ruta"));

        jtfdMarcaB.setHint("Ingrese su Marca");
        jtfdMarcaB.setTipoTextBox(null);
        jtfdMarcaB.setTiponumero(null);
        jtfdMarcaB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfdMarcaBActionPerformed(evt);
            }
        });

        jLabel2.setText("Ruta:");

        jbtnActivar.setText("...");
        jbtnActivar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbtnActivar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnActivarActionPerformed(evt);
            }
        });

        jbtnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/save.png"))); // NOI18N
        jbtnGuardar.setText("Restaurar BK");
        jbtnGuardar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbtnGuardar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jbtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jtfdMarcaB, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtnActivar))
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(jbtnGuardar)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtfdMarcaB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbtnActivar)))
                .addGap(0, 15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public static int idcat = 0;
    public static String estado = "", est = "",ruta_dump="",ruta_guardar="";
    public static boolean modif = false;
    DefaultTableModel dtm = null;
    
    private void jbtnActivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnActivarActionPerformed
        try {
            JFileChooser fileChooser = new JFileChooser();
            FileNameExtensionFilter filter = new FileNameExtensionFilter("SQL File","sql");
            fileChooser.addChoosableFileFilter(filter);
            fileChooser.setFileFilter(filter);
            if (fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
                File file = fileChooser.getSelectedFile();
                String ruta = file.getAbsolutePath();
                System.out.println("ruta: " + ruta);
                jtfdMarcaB.setText(ruta);
                ruta_guardar = ruta;
                // save to file
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.toString());
        }
    }//GEN-LAST:event_jbtnActivarActionPerformed

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
    }//GEN-LAST:event_formInternalFrameActivated

    private void jbtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnGuardarActionPerformed
        try {
            
            for (Parametros object : ParametrosADN.Lista()) {
                ruta_dump = object.getRuta_dump();
            }
            if (ruta_dump.equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Ingrese la ruta del archivo de generación de "
                        + "bk en la ventana de parámetros");
                return;
            }
            ParametrosADN.EliminaDB();
            ParametrosADN.CreaDB();
//            String ruta_d = (ruta_dump + " -uroot -p542047 dbbodega < "+ruta_guardar).replace("mysqldump.exe", "mysql");
            String ruta_d = "cmd "+ruta_dump.replace("/mysqldump.exe", "")+" mysql --user=root --password=542047   dbbodega < " +ruta_guardar+".sql";
            System.out.println(ruta_d);
            Process child = Runtime.getRuntime().exec(ruta_d);
            
//            Process p = Runtime.getRuntime().exec(ruta_dump + " -u root -p 542047 dbbodega -r "+ruta_guardar+".sql");
//             Runtime runtime = Runtime.getRuntime();
//              Process child = runtime.exec(ruta_d); 
              JOptionPane.showMessageDialog(rootPane, "La Base de Datos ha sido Restaurada Correctamente");
//            InputStream is = p.getInputStream();
//            FileOutputStream fos = new FileOutputStream(ruta_guardar + ".sql");
//            byte[] buffer = new byte[1000];
//
//            int leido = is.read(buffer);
//            while (leido > 0) {
//                fos.write(buffer, 0, leido);
//                leido = is.read(buffer);
//            }
//        os.flush();
//              os.close();
//              fis.close();
//            fos.close();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.toString());
        }
    }//GEN-LAST:event_jbtnGuardarActionPerformed

    private void jtfdMarcaBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfdMarcaBActionPerformed
    }//GEN-LAST:event_jtfdMarcaBActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtnActivar;
    private javax.swing.JButton jbtnGuardar;
    private org.swing.componet.JTextBoxHintDS jtfdMarcaB;
    // End of variables declaration//GEN-END:variables
}
