/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package FormInternos;

import Controles.PanelAC;
import static FormInternos.JIVentas.llamada_venta;
import javax.swing.JOptionPane;
import accesodatos.ParametrosADN;
import entidades.Formatos;
import entidades.Parametros;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author EDWARD
 */
public class JDCobrar extends javax.swing.JDialog {

    /**
     * Creates new form JDCobrar
     */
    public JDCobrar(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.getRootPane().setDefaultButton(btncobrar);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtfdMonto = new org.swing.componet.JTextBoxHintDS();
        jtfdBillete = new org.swing.componet.JTextBoxHintDS();
        jtfdVuelto = new org.swing.componet.JTextBoxHintDS();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtfdBillete1 = new org.swing.componet.JTextBoxHintDS();
        jtfdBillete2 = new org.swing.componet.JTextBoxHintDS();
        jPanel2 = new javax.swing.JPanel();
        btncobrar = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(":: Cobro de Efectivo ::");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Cobrar"));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel1.setText("Monto:");

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel2.setText("Paga con:");

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel3.setText("Vuelto:");
        jLabel3.setToolTipText("");

        jtfdMonto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfdMonto.setHint("S/. 0.00");
        jtfdMonto.setTiponumero(org.Interfaces.Enum.TiposNumeros.Decimal);

        jtfdBillete.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfdBillete.setHint("S/. 0.00");
        jtfdBillete.setTiponumero(org.Interfaces.Enum.TiposNumeros.Decimal);
        jtfdBillete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfdBilleteActionPerformed(evt);
            }
        });

        jtfdVuelto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfdVuelto.setHint("S/. 0.00");
        jtfdVuelto.setTiponumero(org.Interfaces.Enum.TiposNumeros.Decimal);

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel4.setText("Descuento:");

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel5.setText("%");

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel6.setText("A cuenta:");

        jtfdBillete1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfdBillete1.setText("0");
        jtfdBillete1.setHint("S/. 0.00");
        jtfdBillete1.setTiponumero(org.Interfaces.Enum.TiposNumeros.Decimal);
        jtfdBillete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfdBillete1ActionPerformed(evt);
            }
        });
        jtfdBillete1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtfdBillete1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfdBillete1FocusLost(evt);
            }
        });
        jtfdBillete1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfdBillete1KeyTyped(evt);
            }
        });

        jtfdBillete2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfdBillete2.setText("0");
        jtfdBillete2.setTiponumero(org.Interfaces.Enum.TiposNumeros.Decimal);
        jtfdBillete2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfdBillete2ActionPerformed(evt);
            }
        });
        jtfdBillete2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfdBillete2FocusLost(evt);
            }
        });
        jtfdBillete2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfdBillete2KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jLabel6))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfdMonto, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                            .addComponent(jtfdBillete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtfdVuelto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtfdBillete1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jtfdBillete2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtfdMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jtfdBillete2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtfdBillete1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfdBillete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtfdVuelto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btncobrar.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btncobrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/money.png"))); // NOI18N
        btncobrar.setText("Cobrar");
        btncobrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncobrarActionPerformed(evt);
            }
        });
        btncobrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btncobrarKeyPressed(evt);
            }
        });

        btncancelar.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btncancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/elimi.png"))); // NOI18N
        btncancelar.setText("Cancelar");
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(btncobrar)
                .addGap(18, 18, 18)
                .addComponent(btncancelar)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btncobrar)
                    .addComponent(btncancelar))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        if (JIVentas.llamada_venta) {
            jtfdMonto.setText(String.valueOf(JIVentas.total));
//            jtfdBillete1.setText(String.valueOf(JIVentas.total));
            
        }else
        {
            jtfdMonto.setText(String.valueOf(JIListaVentasPendientes.total));
//            jtfdBillete1.setText(String.valueOf(JIVentas.total));
            
        }   
        jtfdBillete2.requestFocus();
        jtfdBillete2.setSelectionStart(0);
        jtfdBillete2.setSelectionEnd(jtfdBillete2.getText().length());
//        if (JIListaVentasPendientes.is_acuenta) {
//            
//            jtfdBillete1.setEnabled(false);
//        }else
//        {
//            jtfdBillete1.setEnabled(true);
//        }
        if (JIVentas.llamada_venta) {
            jtfdBillete1.setEnabled(true);
            jtfdBillete2.setEnabled(true);
        }else
        {
            jtfdBillete1.setEnabled(false);
            if (JIListaVentasPendientes.descuento>0) {
                jtfdBillete2.setEnabled(false);
                jtfdBillete.requestFocus();
            }else
            {
                jtfdBillete2.setEnabled(true);
            }
        }
    }//GEN-LAST:event_formWindowOpened

    private void btncobrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncobrarActionPerformed
        try {
            if (jtfdBillete.getText().trim().length() > 0) {
                float b = Float.parseFloat(jtfdBillete.getText());
                float descuento = Float.parseFloat(jtfdBillete2.getText())/100f;
                float a_cuenta = Float.parseFloat(jtfdBillete1.getText());
                if (a_cuenta>b) {
                    JOptionPane.showMessageDialog(rootPane, "El monto a cuenta no puede ser mayor al total de la venta");
                    return;
                }
                float a_pagar = 0f;
                a_pagar = a_cuenta>0?a_cuenta:(Float.parseFloat(jtfdMonto.getText()) -descuento);
                if (b >= a_pagar) {
                    if (JIVentas.llamada_venta) {
                        JIVentas.montopagado = b;
                        JIVentas.recidido = b;
                        JIVentas.vuelto = Float.parseFloat(jtfdVuelto.getText());
                        JIVentas.estado_cobro = true;
                        JIVentas.a_cuenta=a_cuenta;
                        JIVentas.descuento=JIVentas.total*descuento;
                        llamada_venta = false;
                        dispose();
                    }else
                    {
                        JIListaVentasPendientes.montopagado = b;
                        JIListaVentasPendientes.recidido = b;
                        JIListaVentasPendientes.vuelto = Float.parseFloat(jtfdVuelto.getText());
                        JIListaVentasPendientes.estado = true;
                        JIListaVentasPendientes.descuento=JIListaVentasPendientes.total*descuento;
//                        if (a_cuenta>0 ) {
//                            JOptionPane.showMessageDialog(rootPane, "Debe cancelar el total de la venta");
//                            return;
//                        }
                        JIListaVentasPendientes.a_cuenta=a_cuenta;
                        JIListaVentasPendientes.is_acuenta=false;
                        dispose();
                    }
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Ingrese nuevamente la cantidad");
        }

    }//GEN-LAST:event_btncobrarActionPerformed

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        JIVentas.estado_cobro = false;
        dispose();
        
    }//GEN-LAST:event_btncancelarActionPerformed

    private void jtfdBilleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfdBilleteActionPerformed
        try {
            if (jtfdBillete.getText().trim().length() > 0) {
                float b = Float.valueOf(jtfdBillete.getText());
                float d = b - (Float.parseFloat(Float.parseFloat(jtfdBillete1.getText().toString()) >0?jtfdBillete1.getText(): jtfdMonto.getText()));
                double e = Math.rint(Double.valueOf(String.valueOf(d)) * 100) / 100;
                jtfdVuelto.setText(String.valueOf(e));
                btncobrar.requestFocus();
                PanelAC.pintartext(jPanel1);
            }
        }catch (Exception e) {
        }

    }//GEN-LAST:event_jtfdBilleteActionPerformed

    private void btncobrarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btncobrarKeyPressed
        if (evt.getKeyChar() <= (char) 13) {
            btncobrarActionPerformed(null);
        }
        
    }//GEN-LAST:event_btncobrarKeyPressed

    private void jtfdBillete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfdBillete1ActionPerformed
//        float total0 =  JIVentas.llamada_venta?JIVentas.total:JIListaVentasPendientes.total;
//        float descuento = total0 * Float.parseFloat(jtfdBillete2.getText().toString())/100;
//        float a_cuenta = Float.parseFloat(jtfdBillete1.getText().toString());
//        jtfdMonto.setText(Formatos.df.format(total0- descuento- a_cuenta));
//        if (jtfdBillete1.getText().length()==0) {
//            jtfdBillete1.setText("0");
//        }
        jtfdBillete.requestFocus();
    }//GEN-LAST:event_jtfdBillete1ActionPerformed

    private void jtfdBillete1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfdBillete1KeyTyped
        
    }//GEN-LAST:event_jtfdBillete1KeyTyped

    private void jtfdBillete2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfdBillete2ActionPerformed
        float total =  JIVentas.llamada_venta?JIVentas.total:JIListaVentasPendientes.total;
        float descuento = Float.parseFloat(jtfdBillete2.getText().toString())/100;
        jtfdMonto.setText(Formatos.df.format(total - total*descuento));
        jtfdBillete1.setSelectionStart(0);
        jtfdBillete1.setSelectionEnd(jtfdBillete1.getText().length());
        jtfdBillete1.setText("0");
        jtfdBillete1.requestFocus();
    }//GEN-LAST:event_jtfdBillete2ActionPerformed

    private void jtfdBillete2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfdBillete2KeyTyped
        
    }//GEN-LAST:event_jtfdBillete2KeyTyped

    private void jtfdBillete2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfdBillete2FocusLost
         if (jtfdBillete2.getText().length()==0) {
            jtfdBillete2.setText("0");
        }else
        {
            jtfdBillete2ActionPerformed(null);
        }
        if (JIListaVentasPendientes.is_acuenta) {
            jtfdBillete.requestFocus();
            
            jtfdBillete.setSelectionStart(0);
            jtfdBillete.setSelectionEnd(jtfdBillete2.getText().length());
        }else
        {
            jtfdBillete1.requestFocus();
            jtfdBillete1.setText("0");
            jtfdBillete1.setSelectionStart(0);
            jtfdBillete1.setSelectionEnd(jtfdBillete2.getText().length());
        }
        
    }//GEN-LAST:event_jtfdBillete2FocusLost

    private void jtfdBillete1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfdBillete1FocusLost
        if (jtfdBillete1.getText().length()==0) {
            jtfdBillete1.setText("0");
        }
    }//GEN-LAST:event_jtfdBillete1FocusLost

    private void jtfdBillete1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfdBillete1FocusGained
//        jtfdBillete1.setText("0"); 
    }//GEN-LAST:event_jtfdBillete1FocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDCobrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDCobrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDCobrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDCobrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDCobrar dialog = new JDCobrar(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btncobrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private org.swing.componet.JTextBoxHintDS jtfdBillete;
    private org.swing.componet.JTextBoxHintDS jtfdBillete1;
    private org.swing.componet.JTextBoxHintDS jtfdBillete2;
    private org.swing.componet.JTextBoxHintDS jtfdMonto;
    private org.swing.componet.JTextBoxHintDS jtfdVuelto;
    // End of variables declaration//GEN-END:variables
}
