/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package FormInternos;

import Adicional.*;
import accesodatos.*;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.BaseFont;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import entidades.*;
import java.awt.Desktop;
import java.io.File;
import java.io.FileOutputStream;
import java.io.OutputStream;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author EDWARD
 */
public class JIConsultaProductos2 extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIConsultaProductos
     */
    public JIConsultaProductos2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btnimprimir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        tbxtotal = new javax.swing.JTextField();
        tbxnroventas = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Productos pendientes de entrega");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Filtro"));

        btnimprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Print2.png"))); // NOI18N
        btnimprimir.setText("Imprimir");
        btnimprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnimprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnimprimir)
                .addGap(352, 352, 352))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnimprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nro venta", "Fecha venta", "Fecha recojo", "Cantidad", "Descripcion", "Precio venta", "Importe"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        tbxtotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel3.setText("Total valores:");

        jLabel1.setText("Nro de registros:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tbxnroventas, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 609, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tbxtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tbxnroventas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tbxtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    DefaultTableModel dtm = null;
    
    private void btnimprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnimprimirActionPerformed
        Imprimir();
    }//GEN-LAST:event_btnimprimirActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        dtm = (DefaultTableModel) jTable1.getModel();
        try {
           
            
            Util.ModificarTamañoJtable(jTable1,0,120);
            Util.ModificarTamañoJtable(jTable1,1,90);
            Util.ModificarTamañoJtable(jTable1,2,140);
            Util.ModificarTamañoJtable(jTable1,3,80);
            Util.ModificarTamañoJtable(jTable1,4,290);
            Util.ModificarTamañoJtable(jTable1,5,70);
            Util.ModificarTamañoJtable(jTable1,6,70);
            VerDatos();
            int nrofilas = 0;
            float totalventas = 0;
            int filas = jTable1.getRowCount();
            for (int i = 0; i < filas; i++) {
                nrofilas += 1;
                tbxnroventas.setText(String.valueOf(nrofilas));
                totalventas += Float.parseFloat(dtm.getValueAt(i, 6).toString());
                tbxtotal.setText(Formatos.df.format(totalventas));
            }
            
            DefaultTableCellRenderer tcr = new DefaultTableCellRenderer();
            tcr.setHorizontalAlignment(SwingConstants.RIGHT);
            jTable1.getColumnModel().getColumn(3).setCellRenderer(tcr);
            
            tcr.setHorizontalAlignment(SwingConstants.RIGHT);
            jTable1.getColumnModel().getColumn(5).setCellRenderer(tcr);
            
            tcr.setHorizontalAlignment(SwingConstants.RIGHT);
            jTable1.getColumnModel().getColumn(6).setCellRenderer(tcr);
        }catch(Exception ex)
        {   
            System.out.println("ex: "+ex.toString());
        }
        
    }//GEN-LAST:event_formInternalFrameOpened

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnimprimir;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField tbxnroventas;
    private javax.swing.JTextField tbxtotal;
    // End of variables declaration//GEN-END:variables

    private void VerDatos() throws SQLException, ClassNotFoundException {
        try {
            int filas = jTable1.getRowCount();
            for (int i = 0; i < filas; i++) {
                dtm.removeRow(0);
            }
            for (ConsultaVentas la : VentasADN.ConsultaProductos("%",
                                                                 "%",
                                                                 "%")) {
                dtm.addRow(la.ArregloDatosP());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.toString());
        }
    }

    void Imprimir() {
        try {
            //creamos un documento
            Document doc = new Document(PageSize.A4.rotate(), 30f, 20f, 50f, 20f);
            OutputStream archivo = new FileOutputStream("Reporte_productos2.pdf");
            PdfWriter.getInstance(doc, archivo);

            //abrimos el archivo
            doc.open();
            Paragraph encabezado = new Paragraph("Reporte de productos pendiente de entrega", FontFactory.getFont("arial", 24, Font.BOLD));
            encabezado.setAlignment(encabezado.ALIGN_CENTER);
            Paragraph separacion = new Paragraph("\n");
//            Paragraph fecha1 = new Paragraph("Del: " + Formatos.sdfFecha.format(snrfecha.getValue())+"   "+"Al: " + Formatos.sdfFecha.format(snrfecha.getValue()));
//            fecha1.setAlignment(fecha1.ALIGN_CENTER);
//            Paragraph fecha2 = new Paragraph();
            Paragraph linea = new Paragraph("----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------");

            BaseFont tipo = BaseFont.createFont(BaseFont.HELVETICA, BaseFont.CP1252, false);
            Font fuente = new Font(tipo, 13, Font.BOLD, BaseColor.BLUE);
            Paragraph totales = new Paragraph("Nro registros: " + tbxnroventas.getText() + "                                                                                                                                                                             " + "Total: " + tbxtotal.getText(), fuente);

            //creamos la tabla para las filas del jtable
            PdfPTable tabla = new PdfPTable(8);
            tabla.getDefaultCell().setBorder(1);
            tabla.getDefaultCell().setBackgroundColor(BaseColor.LIGHT_GRAY);
            int[] ancho = new int[]{50,180,80,170, 70, 280, 60,60};
            tabla.setWidths(ancho);
            tabla.setSpacingBefore(50);
            tabla.setWidthPercentage(100);
            tabla.addCell("Nro");
            tabla.addCell("Nro venta");
            tabla.addCell("Fec venta");
            tabla.addCell("Fec recojo");
            tabla.addCell("Cantidad");
            tabla.addCell("Descripción");
            tabla.addCell("Prec_");
            tabla.addCell("Importe");
            PdfPTable tabla2 = new PdfPTable(8);
            tabla2.getDefaultCell().setBorder(0);

            tabla2.setWidths(ancho);
            tabla2.setWidthPercentage(100);

            int filas = jTable1.getRowCount();
            for (int i = 0; i < filas; i++) {
                PdfPCell cell = new PdfPCell(new Phrase(String.valueOf(i+1), new com.itextpdf.text.Font(tipo, 9, com.itextpdf.text.Font.BOLD, BaseColor.BLACK)));
                cell.setBorderWidthBottom(1);
                tabla.addCell(cell);
                
                cell = new PdfPCell(new Phrase(dtm.getValueAt(i, 0).toString(), new com.itextpdf.text.Font(tipo, 9, com.itextpdf.text.Font.BOLD, BaseColor.BLACK)));
                cell.setBorderWidthBottom(1);
                tabla.addCell(cell);
                
                cell = new PdfPCell(new Phrase(dtm.getValueAt(i,1).toString(), new com.itextpdf.text.Font(tipo, 9, com.itextpdf.text.Font.BOLD, BaseColor.BLACK)));
                cell.setBorderWidthBottom(1);
                tabla.addCell(cell);
                
                cell = new PdfPCell(new Phrase(dtm.getValueAt(i, 2).toString(), new com.itextpdf.text.Font(tipo, 9, com.itextpdf.text.Font.BOLD, BaseColor.BLACK)));
                cell.setBorderWidthBottom(1);
                tabla.addCell(cell);
                
                cell = new PdfPCell(new Phrase(dtm.getValueAt(i, 3).toString(), new com.itextpdf.text.Font(tipo, 9, com.itextpdf.text.Font.BOLD, BaseColor.BLACK)));
                cell.setBorderWidthBottom(1);
                cell.setHorizontalAlignment(Element.ALIGN_RIGHT);
                tabla.addCell(cell);
                
                cell = new PdfPCell(new Phrase(dtm.getValueAt(i, 4).toString(), new com.itextpdf.text.Font(tipo, 9, com.itextpdf.text.Font.BOLD, BaseColor.BLACK)));
                cell.setBorderWidthBottom(1);
                tabla.addCell(cell);
                
                cell = new PdfPCell(new Phrase(dtm.getValueAt(i, 5).toString(), new com.itextpdf.text.Font(tipo, 9, com.itextpdf.text.Font.BOLD, BaseColor.BLACK)));
                cell.setBorderWidthBottom(1);
                cell.setHorizontalAlignment(Element.ALIGN_RIGHT);
                tabla.addCell(cell);
                
                cell = new PdfPCell(new Phrase(dtm.getValueAt(i, 6).toString(), new com.itextpdf.text.Font(tipo, 9, com.itextpdf.text.Font.BOLD, BaseColor.BLACK)));
                cell.setBorderWidthBottom(1);
                cell.setHorizontalAlignment(Element.ALIGN_RIGHT);
                tabla.addCell(cell);
                
            }
            //le añadimos los elementos al documento
            doc.add(encabezado);
//            doc.add(fecha1);
            doc.add(tabla);
            doc.add(tabla2);
            doc.add(linea);
            doc.add(totales);
            doc.close();
            archivo.close();

            //abrir el documento
            File arch = new File("Reporte_productos2.pdf");
            Desktop.getDesktop().open(arch);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Error al imprimir reporte");
        }
    }
}
