/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package FormInternos;

import accesodatos.ComprasADN;
import accesodatos.ProductosADN;
import entidades.Compras;
import entidades.Detalle_Compra;
import entidades.Formatos;
import entidades.ProductoDetalle;
import entidades.Productos;
import java.awt.Color;
import java.sql.Date;
import java.util.LinkedList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Crixuz
 */
public class JICompras extends javax.swing.JInternalFrame {

    /**
     * Creates new form JICompras
     */
    public JICompras() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jbtnNuevo = new javax.swing.JButton();
        jbtnAgregar = new javax.swing.JButton();
        jbtnQuitar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jteLista = new javax.swing.JTable();
        jbtnCompra = new javax.swing.JButton();
        jlabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jbtnBProveedor = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cbxtipodocumento = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jdprFecCompra = new com.michaelbaranov.microba.calendar.DatePicker();
        jtfdProveedor = new org.swing.componet.JTextBoxHintDS();
        jtfdNroDocumento = new org.swing.componet.JTextBoxHintDS();
        jLabel4 = new javax.swing.JLabel();
        jtfdSubTotal = new org.swing.componet.JTextBoxHintDS();
        jtfdIgv = new org.swing.componet.JTextBoxHintDS();
        jtfdTotal = new org.swing.componet.JTextBoxHintDS();

        setClosable(true);
        setTitle("::::::>>>> Compras de Productos <<<<::::::");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jbtnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/ven2_result.png"))); // NOI18N
        jbtnNuevo.setText("Nuevo");
        jbtnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNuevoActionPerformed(evt);
            }
        });

        jbtnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/ven3_result.png"))); // NOI18N
        jbtnAgregar.setText("Agregar");
        jbtnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAgregarActionPerformed(evt);
            }
        });

        jbtnQuitar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/ven4_result.png"))); // NOI18N
        jbtnQuitar.setText("Quitar");
        jbtnQuitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnQuitarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbtnNuevo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnQuitar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnAgregar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbtnNuevo)
                .addGap(18, 18, 18)
                .addComponent(jbtnAgregar)
                .addGap(18, 18, 18)
                .addComponent(jbtnQuitar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel6.setText("IGV:");

        jteLista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IdProducto", "Cantidad", "Descripcion de Producto", "Precio", "Importe"
            }
        ));
        jScrollPane1.setViewportView(jteLista);
        jteLista.getColumnModel().getColumn(0).setMinWidth(0);
        jteLista.getColumnModel().getColumn(0).setPreferredWidth(0);
        jteLista.getColumnModel().getColumn(0).setMaxWidth(0);
        jteLista.getColumnModel().getColumn(1).setMinWidth(80);
        jteLista.getColumnModel().getColumn(1).setPreferredWidth(80);
        jteLista.getColumnModel().getColumn(1).setMaxWidth(80);
        jteLista.getColumnModel().getColumn(3).setMinWidth(100);
        jteLista.getColumnModel().getColumn(3).setPreferredWidth(100);
        jteLista.getColumnModel().getColumn(3).setMaxWidth(100);
        jteLista.getColumnModel().getColumn(4).setMinWidth(120);
        jteLista.getColumnModel().getColumn(4).setPreferredWidth(120);
        jteLista.getColumnModel().getColumn(4).setMaxWidth(120);

        jbtnCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/ven1_result.png"))); // NOI18N
        jbtnCompra.setText("Comprar");
        jbtnCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCompraActionPerformed(evt);
            }
        });

        jlabel.setText("Total:");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos de Compra"));

        jLabel1.setText("Proveedor");

        jbtnBProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Find.png"))); // NOI18N
        jbtnBProveedor.setEnabled(false);
        jbtnBProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBProveedorActionPerformed(evt);
            }
        });

        jLabel2.setText("Tipo Documiento:");

        cbxtipodocumento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Boleta", "Factura" }));
        cbxtipodocumento.setEnabled(false);

        jLabel3.setText("Nº Documento:");

        jLabel7.setText("Fecha Compra:");

        jdprFecCompra.setEnabled(false);

        jtfdProveedor.setEditable(false);
        jtfdProveedor.setText("SIN PROVEEDOR");
        jtfdProveedor.setHint("Datos del Proveedor");
        jtfdProveedor.setTipoTextBox(null);
        jtfdProveedor.setTiponumero(null);

        jtfdNroDocumento.setEditable(false);
        jtfdNroDocumento.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfdNroDocumento.setHint("000000");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jtfdProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtnBProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jLabel7))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cbxtipodocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jtfdNroDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jdprFecCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(163, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jdprFecCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbtnBProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jtfdProveedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbxtipodocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfdNroDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setText("SubTotal:");

        jtfdSubTotal.setEditable(false);
        jtfdSubTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfdSubTotal.setHint("S/. 0.00");
        jtfdSubTotal.setTiponumero(org.Interfaces.Enum.TiposNumeros.Decimal);

        jtfdIgv.setEditable(false);
        jtfdIgv.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfdIgv.setHint("S/. 0.00");
        jtfdIgv.setTiponumero(org.Interfaces.Enum.TiposNumeros.Decimal);

        jtfdTotal.setEditable(false);
        jtfdTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfdTotal.setHint("S/. 0.00");
        jtfdTotal.setTiponumero(org.Interfaces.Enum.TiposNumeros.Decimal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtnCompra)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlabel, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfdIgv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtfdSubTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtfdTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtnCompra)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfdSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfdIgv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfdTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlabel))))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public static int idprov = 0, idpro = 0;
    public static boolean llamada = false;
    public static String nomprov = "", nomprod = "";
    LinkedList<Productos> Lista = new LinkedList<>();
    private float subtotal = 0;
    public static ProductoDetalle ProX = new ProductoDetalle();
    private DefaultTableModel dtm = null;
    private void jbtnBProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBProveedorActionPerformed
        JDBuscarProveedor v = new JDBuscarProveedor(null, closable);
        v.setLocationRelativeTo(this);
        v.setVisible(true);
        if (idprov > 0) {
            jtfdProveedor.setText(nomprov);
            jtfdProveedor.setForeground(Color.BLACK);
        } else {
            jtfdProveedor.setText("");
            idprov = 0;
        }
    }//GEN-LAST:event_jbtnBProveedorActionPerformed

    private void jbtnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAgregarActionPerformed
        ProX = new ProductoDetalle();
        llamada = true;
        JDBuscarProductos v = new JDBuscarProductos(null, closable);
        v.setLocationRelativeTo(this);
        v.setVisible(true);

        if (ProX.getIdProducto() > 0) {
            int nro = jteLista.getRowCount();
            int aux = 0;
            float impA = 0, preA = 0, canA = 0;
//            JOptionPane.showMessageDialog(rootPane, "waaaa");
            boolean estado = false;
            for (int f = 0; f < nro; f++) {
                aux = Integer.parseInt(dtm.getValueAt(f, 0).toString());
                if (aux == ProX.getIdProducto()) {
                    estado = true;
                    preA = Float.parseFloat(dtm.getValueAt(f, 3).toString());
                    canA = Float.parseFloat(dtm.getValueAt(f, 1).toString());
                    impA = Float.parseFloat(dtm.getValueAt(f, 4).toString());
                    canA += ProX.getCantidad();
                    ProX.setImporte(preA * canA);
                    subtotal -= impA;
                    subtotal += ProX.getImporte();
                    dtm.setValueAt(String.valueOf(canA), f, 1);
                    dtm.setValueAt(String.valueOf(ProX.getImporte()), f, 4);
                    break;
                }
            }
            if (estado == false) {
                dtm.addRow(ProX.DatosToArray());
                subtotal += ProX.getImporte();
            }
            VerTotales();
        }
        llamada = false;
    }//GEN-LAST:event_jbtnAgregarActionPerformed

    private void jbtnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNuevoActionPerformed
        if (jbtnNuevo.getText().equals("Nuevo")) {
            jbtnNuevo.setText("Cancelar");
            Habilitar(true);
            jbtnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/cancelar1.png")));
        } else {
            Habilitar(false);
            jbtnNuevo.setText("Nuevo");
            jbtnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/ven2_result.png")));
        }
        Limpiar();
        subtotal = 0;
        VerTotales();
        idprov = 1;
    }//GEN-LAST:event_jbtnNuevoActionPerformed

    private void jbtnQuitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnQuitarActionPerformed
        int f = jteLista.getSelectedRow();
        if (f >= 0) {
            float impA = Float.parseFloat(dtm.getValueAt(f, 4).toString());
            subtotal -= impA;
            VerTotales();
            dtm.removeRow(f);
        }
    }//GEN-LAST:event_jbtnQuitarActionPerformed

    private void jbtnCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCompraActionPerformed
        try {
            if (jteLista.getRowCount() > 0) {
                if (jtfdNroDocumento.getText().length() <= 0) {
                    JOptionPane.showMessageDialog(jbtnCompra, "Ingrese Nro de docuemnto de compra");
                } else {
                    Compras aux = new Compras();
                    aux.setIdCompra(0);
//                Clientes c= new Clientes();
//                c.setIdCliente(idcli);
                    aux.setIdProveedor(idprov);
                    aux.setTipodoc(cbxtipodocumento.getSelectedItem().toString());
                    aux.setNro(jtfdNroDocumento.getText().trim());
                    String fecha = Formatos.sdfFecha.format(jdprFecCompra.getDate());
                    Date fechasql = Formatos.FechaSQL(fecha);
                    aux.setFecha(fechasql);
                    aux.setTotal(Float.parseFloat(jtfdTotal.getText()));
                    aux.setIgv(Float.parseFloat(jtfdIgv.getText()));
                    aux.setSubtotal(Float.parseFloat(jtfdSubTotal.getText()));
                    aux.setEstado("1");
                    LinkedList<Detalle_Compra> dv = new LinkedList<>();
                    Detalle_Compra d = null;
                    int nr = jteLista.getRowCount();
                    for (int f = 0; f < nr; f++) {
                        d = new Detalle_Compra();
                        d.setIdProducto(Integer.parseInt(dtm.getValueAt(f, 0).toString()));
                        d.setCantidad(Float.parseFloat(dtm.getValueAt(f, 1).toString()));
                        d.setPrecio(Float.parseFloat(dtm.getValueAt(f, 3).toString()));
                        d.setImporte(Float.parseFloat(dtm.getValueAt(f, 4).toString()));
                        dv.add(d);
                    }
                    aux.setLista(dv);
                    boolean estado = ComprasADN.Guardar(aux);
                    if (estado) {
                        JOptionPane.showMessageDialog(rootPane, ":. Compra Realizada .:");
                        for (int f = 0; f < nr; f++) {
                            Productos p = new Productos();
                            p.setStock(Float.parseFloat(dtm.getValueAt(f, 1).toString()));
                            p.setIdProducto(Integer.parseInt(dtm.getValueAt(f, 0).toString()));
                            ProductosADN.AñadirStock(p);
                        }
                        jbtnNuevoActionPerformed(evt);
                    }
                }


            }
        } catch (Exception exception) {
            JOptionPane.showMessageDialog(rootPane, exception.toString());
        }
    }//GEN-LAST:event_jbtnCompraActionPerformed

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        Habilitar(false);
        dtm = (DefaultTableModel) jteLista.getModel();
        jtfdProveedor.setText("SIN PROVEEDOR");
    }//GEN-LAST:event_formInternalFrameActivated
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbxtipodocumento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnAgregar;
    private javax.swing.JButton jbtnBProveedor;
    private javax.swing.JButton jbtnCompra;
    private javax.swing.JButton jbtnNuevo;
    private javax.swing.JButton jbtnQuitar;
    private com.michaelbaranov.microba.calendar.DatePicker jdprFecCompra;
    private javax.swing.JLabel jlabel;
    private javax.swing.JTable jteLista;
    private org.swing.componet.JTextBoxHintDS jtfdIgv;
    private org.swing.componet.JTextBoxHintDS jtfdNroDocumento;
    private org.swing.componet.JTextBoxHintDS jtfdProveedor;
    private org.swing.componet.JTextBoxHintDS jtfdSubTotal;
    private org.swing.componet.JTextBoxHintDS jtfdTotal;
    // End of variables declaration//GEN-END:variables

    private void Habilitar(boolean cs) {
        jbtnAgregar.setEnabled(cs);
        jbtnBProveedor.setEnabled(cs);
        jbtnQuitar.setEnabled(cs);
        jbtnCompra.setEnabled(cs);
        cbxtipodocumento.setEnabled(cs);
        jdprFecCompra.setEnabled(cs);
        jtfdNroDocumento.setEditable(cs);
    }

//    private void VerDocumento() {
//        String doc = cbxtipodocumento.getSelectedItem().toString().trim();
//        String GenerarNro = comp.GeneraNro(doc);
//        String GenerarSerie = VentasADN.GenerarSerie(doc);
//        tbxserie.setText(GenerarSerie);
//        tbxnrodocumento.setText(GenerarNro);
//    }
    private void Limpiar() {
//        tbxproveedor.setText("");
        idprov = 0;
        jtfdNroDocumento.setText("");
        int nr = jteLista.getRowCount();
        for (int i = 0; i < nr; i++) {
            dtm.removeRow(0);
        }
    }

    private void VerTotales() {
        String doc = cbxtipodocumento.getSelectedItem().toString();
        float igv = 0, tot = subtotal;
        if (doc.equals("Factura")) {
            igv = subtotal * 0.19f;
            tot = subtotal + igv;
        }
        jtfdSubTotal.setText(Formatos.df.format(subtotal));
        jtfdIgv.setText(Formatos.df.format(igv));
        jtfdTotal.setText(Formatos.df.format(tot));
    }
}
